# Generated by Django 4.2.6 on 2023-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('src_ip', models.CharField(max_length=50)),
                ('dst_ip', models.CharField(max_length=50)),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('device_id', 'Device Id'), ('port', 'Port'), ('src_ip', 'Src Ip'), ('dst_ip', 'Dst Ip')], max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeResponseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('drop', 'Drop')], max_length=50)),
                ('conditions', models.ManyToManyField(to='decision_module.crcondition')),
            ],
        ),
    ]
