# Generated by Django 4.2.6 on 2023-11-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_module', '0003_alter_challengeresponseentity_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='device_id',
            new_name='device_ip',
        ),
        migrations.AlterField(
            model_name='crcondition',
            name='field_name',
            field=models.CharField(choices=[('device_ip', 'Device Ip'), ('port', 'Port'), ('src_ip', 'Src Ip'), ('dst_ip', 'Dst Ip')], max_length=50),
        ),
    ]
