# Generated by Django 4.2.6 on 2023-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('controller', 'Controller'), ('host', 'Host'), ('firewall', 'Firewall'), ('ids', 'Ids'), ('ips', 'Ips'), ('router', 'Router'), ('load_balancer', 'Load Balancer'), ('vpn_gateway', 'Vpn Gateway'), ('cloud', 'Cloud'), ('other', 'Other')], default='other', max_length=50)),
                ('device_secret', models.CharField(max_length=50, unique=True)),
                ('device_ip', models.CharField(max_length=50, unique=True)),
                ('device_port', models.IntegerField()),
            ],
        ),
    ]
