# Generated by Django 4.2.6 on 2023-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateddevice',
            name='device_id',
            field=models.CharField(default='1234', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
