# Generated by Django 4.2.6 on 2023-11-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_authenticateddevice_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticateddevice',
            name='device_port',
        ),
    ]
